#!/usr/bin/env bash
NAME="ax"
FN_SSH_KEY="ssh_key"
HCLOUD_TOKEN="$(pass show HCloudLoisRO)"
HCLOUD_TOKEN_WRITE="$(pass show HCloudLois)"
DNS_API_TOKEN="$(pass show DO/pat)"
HK_HOST_NETWORK=1
LOCATION="hel1"
EMAIL="wackeldackel@quantentunnel.de"
DOMAIN="a1.axlc.net"
DNS_PROVIDER="digitalocean"

d=/home/gk/repos/ax/devapps/gitops
source "$d/main.sh" "$@"

ensure_requirements
#images
#ssh_keys
#ensure_ip_forwarder "37.27.193.230"
#postinstall "37.27.193.230"
ensure_proxy_server
#postinstall "37.27.193.230"
ensure_k3s_via_proxy
ensure_proxy_is_loadbalancer
ensure_local_kubectl

ensure_ingress_nginx_with_certmgr

# test_autoscale
report
#test_autoscale
#ensure_k3s

# For your LSP (shellcheck, allows to jump to the functions via gd):
false && . ./setup.sh && . ./main.sh && . ./pkg/ingress.sh || true
