#!/usr/bin/env bash
NAME="ax"
FN_SSH_KEY="ssh_key"
HCLOUD_TOKEN="$(pass show HCloud/token)"
HOST_NETWORK=4
LOCATION="hel1"
source "./funcs.sh" "$@"
ensure_local_ssh_key # call, when $FN_SSH_KEY possibly not present
check_requirements
#images
#ssh_keys
#ensure_ip_forwarder "37.27.193.230"
#postinstall "37.27.193.230"
ensure_proxy_server
#postinstall "37.27.193.230"
ensure_k3s_via_proxy

#ensure_k3s
