name: Test Workflow

#on: [push, pull_request]
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        env:
          run: "${{ github.event.head_commit.message }}"
          HCLOUD_TOKEN: ${{ secrets.HCRO }}
          HCLOUD_TOKEN_WRITE: ${{ secrets.HCRW }}
        run: |
          if [[ "$run" == *":secrets:"* ]]; then
            bash ./tests/test_secrets.sh
          fi
          if [[ "$run" == *":setup:"* ]]; then
            bash ./tests/test_setup.sh
          fi
          # Add more tests as needed

      - name: Teardown
        if: ${{ !(contains(github.event.head_commit.message, ':keep cluster:')) }}
        run: bash ./tests/teardown.sh
