name: Test Workflow

#on: [push, pull_request]
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PATH: /home/runner/.binenv:/usr/sbin:/usr/bin:/bin:/sbin
      SOPSINST: ${{ secrets.SOPSINST }}
      act: ${{ github.event.head_commit.message }}
      keep: ${{ contains(github.event.head_commit.message, ':keep:') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare
        run: bash ./tests/gh-prepare.sh

      - name: Teardown
        if: contains(env.act, ':rm:')
        run: bash ./tests/teardown.sh

      - name: Test base (secrets, syntax)
        run: bash ./tests/base.sh

      - name: Cluster setup
        if: contains(env.act, ':setup:')
        run: bash ./tests/setup.sh

      - name: Full HTTP Svc Test
        if: contains(env.act, ':setup:')
        run: bash ./tests/setup.sh test_http_svc_nginx

      - name: Flux Tests
        if: contains(env.act, ':flux:')
        run: |
          . tests/environ # exports all secret
          export repo="https://axgkl:$GITOPS_TOKEN@github.com/axgkl/hk3sf-fluxtest.git"
          echo "test repos is: $repo"
          git clone "$repo" fluxrepo
          (
          cd fluxrepo
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          date >> ./last.hk3sf-fluxtest.date
          git add .
          ../tests/flux.sh
          )
      - name: Cat logfile on failure
        if: failure()
        run: cat /home/runner/work/hk3sf/hk3sf/fluxrepo/tmp.citest/install.log

      - name: Teardown
        # runs even if previous steps failed, when keep is not given and setup is given:
        if: ${{ always() && !env.keep && contains(env.act, ':setup:') }}
        run: bash ./tests/teardown.sh
