name: Test Workflow

#on: [push, pull_request]
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HCRO }}
      HCLOUD_TOKEN_WRITE: ${{ secrets.HCRW }}
      DNS_API_TOKEN: ${{ secrets.DORW }}
      DNS_PROVIDER: digitalocean
      DOMAIN: "citest.${{ secrets.DOMAIN }}"
      EMAIL: "${{ secrets.EMAIL }}"
      NAME: "citest"
      FN_SSH_KEY: "ssh_key"
      HK_HOST_NETWORK: 2
      LOCATION: "hel1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test_secrets.sh
        if: contains(github.event.head_commit.message, ':secrets:')
        run: bash ./tests/test_secrets.sh

      - name: Run test_setup.sh
        if: contains(github.event.head_commit.message, ':setup:')
        run: bash ./tests/test_setup.sh

      - name: Teardown
        if: ${{ !(contains(github.event.head_commit.message, ':keep:')) }}
        run: bash ./tests/teardown.sh
