name: Test Workflow

#on: [push, pull_request]
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PATH: /root/.binenv:/usr/sbin:/usr/bin:/bin:/sbin
      AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}
      act: ${{ github.event.head_commit.message }}
      keep: ${{ contains(github.event.head_commit.message, ':keep:') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare
        run: bash ./tests/gh-prepare.sh

      - name: Teardown
        if: contains(env.act, ':rm:')
        run: bash ./tests/teardown.sh

      - name: Test base (secrets, syntax)
        run: bash ./tests/base.sh

      - name: Cluster setup
        if: contains(env.act, ':setup:')
        run: bash ./tests/setup.sh

      - name: Full HTTP Svc Test
        if: contains(env.act, ':setup:')
        run: bash ./tests/setup.sh test_http_svc_nginx

      - name: Teardown
        # runs even if previous steps failed, when keep is not given and setup is given:
        if: ${{ always() && !env.keep && contains(env.act, ':setup:') }}
        run: bash ./tests/teardown.sh
