name: Test Workflow

#on: [push, pull_request]
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NAME: "citest"
      HCLOUD_TOKEN: ${{ secrets.HCRO }}
      HCLOUD_TOKEN_WRITE: ${{ secrets.HCRW }}
      DNS_API_TOKEN: ${{ secrets.DORW }}
      DNS_PROVIDER: digitalocean
      DOMAIN: "citest.${{ secrets.DOMAIN }}"
      EMAIL: "${{ secrets.EMAIL }}"
      SSH_KEY_PRIV: "${{ secrets.SSHKEY }}"
      HK_HOST_NETWORK: 7
      LOCATION: "hel1"
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      act: ${{ github.event.head_commit.message }}
      keep: ${{ contains(github.event.head_commit.message, ':keep:') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Teardown
        if: contains(env.act, ':rm:')
        run: bash ./tests/teardown.sh

      - name: Test base (secrets, syntax)
        run: bash ./tests/test_secrets.sh

      - name: Cluster setup
        if: contains(env.act, ':setup:')
        run: bash ./tests/test_setup.sh

      - name: Full HTTP Svc Test
        if: contains(env.act, ':setup:')
        run: bash ./tests/test_setup.sh test_http_svc_nginx

      - name: Teardown
        if: ${{ always() && !env.keep }}
        run: bash ./tests/teardown.sh
